# Makefile for Documentation of Linux RamDisk
# Systemprogrammierung 
# WS12/13
# Andreas Linz & Tobias Sekan

all: Dokumentation.tex
	@pdflatex Dokumentation.tex

clean:
	@ rm *.log *.aux
 
rmv:
	@ rm *.pdf *.toc